# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='actual_date',
            field=models.DateTimeField(unique=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='image',
            field=models.ImageField(upload_to='img/journalentries'),
        ),
    ]
