# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20170922_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='actual_date',
            field=models.DateField(unique=True),
        ),
    ]
