# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_auto_20170922_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='actual_date',
            field=models.DateField(null=True, unique=True),
        ),
    ]
