# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_auto_20170926_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='quote_author',
            field=models.CharField(default='NULL', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journalentry',
            name='quote_content',
            field=models.TextField(default='NULL', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='actual_date',
            field=models.DateField(unique=True),
        ),
    ]
