# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_auto_20170927_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='quote_author',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='quote_content',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
