# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_auto_20170927_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='posture_changes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='word_of_the_day',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='quote_author',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='quote_content',
            field=models.TextField(max_length=200),
        ),
    ]
