# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_auto_20171030_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='posture_changes',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
